name: Adam Wulf
favicon: null
layout_spectrum: 0.016888774000108242
typography_spectrum: 0.18892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f5ed'
    - '#f8b454'
    - '#408500'
    - '#de8128'
    - '#574e35'
  brandStrength: 0.1370851246174425
  lightness: 0.7371513042598963
  saturation: 0.6149449618533254
  rhythmicContrast: 0.6513710296712816
purpose: []
